### PR TITLE
PassiveManager.cs

### PR DESCRIPTION
**Pull request by ElDivines**
Fixed passive name, Riot changed it in the last patches

### CODE REVIEW

**Review by FlorianRiquelme — APPROVED** [review]

**Comment by FlorianRiquelme** [comment]
;)

**Comment by ElDivines** [comment]
Thanks for approving man :D

**Review by Ox29A — COMMENTED** [review]
idk, i don't use nor do i endorse EloBuddy Anymore :s fork it and change it yourself my friend.

**Comment by Ox29A** [comment]
k fam, go play have fun kappa

**Pull request merged**
